#!/bin/bash
# using an alternative file descriptor

exec 3>&1
exec 1>test14out

echo "This should store in test14out file "
echo "along with this line"

exec 1>&3
echo "Now things should be back to normal"
