#!/bin/bash
# reading values from a file

file="states"

# specify the seperator character
IFS_OLD=$IFS
IFS=$'\n'

for state in $(cat $file)
do
    echo "Now going to visit $state"
done

IFS=$IFS_OLD
